### PR TITLE
Free trial pdf and sql files

### PR DESCRIPTION
**Pull request by hirokib**

### CODE REVIEW

**Comment by hirokib** [comment]
#sign-off

**Comment by barbkess** [comment]
@hirokib Ellis, can you put this into a folder with a more descriptive name?  For example, SQL-Data-Warehouse-free-trial-tutorial

**Comment by barbkess** [comment]
@hirokib, Or create a folder demos/sqldw/sqldw-free-trial-lab so we can put any other sqldw demos in there.

**Comment by hirokib** [comment]
#sign-off

**Comment by jodebrui** [comment]
Please use lower case for folder names. Thanks.

**Comment by jodebrui** [comment]
Hi, can you update the PR to use lower case for folder names?

**Pull request merged**
