### PR TITLE
Add Docker healthcheck

### PR DESCRIPTION
**Pull request by matt-richardson**
Adds healthcheck script to enable checking of when SQL Server is ready

### CODE REVIEW

**Comment by perrysk-msft** [comment]
Thanks for the contribution Matt! 

Good thinking - We are in the middle of testing and merging similar functionality along these lines. We'll close this PL for now to avoid conflicts.

Thanks again!

**Comment by matt-richardson** [comment]
Hi @perrysk-msft - do you have a rough eta for when that will be ready?
Just wondering if I need to create my own image in the interim.

**Comment by perrysk-msft** [comment]
Hi Matt - We do not have an eta for this yet but it should be in the next 2-3 weeks.

**Comment by matt-richardson** [comment]
Hi @perrysk-msft - any update on this?

**Comment by perrysk-msft** [comment]
Hi Matt - Still working on it. We had to shift priorities and put this on hold for now.

**Pull request closed without merging**
