### PR TITLE
Initial checkin for hdfs kerberos testing tool

### PR DESCRIPTION
**Pull request by udlingal**

### CODE REVIEW

**Comment by uc-msft** [comment]
We have a policy of not putting binaries in the samples source. You need to provide the actual code and instructions for how to produce the binary.

**Comment by udlingal** [comment]
This is python notebook which uses a jar file. Should I put this in different place under sql-server-samples? Or should I include source code for jar file and python with binaries(this will increase zip file size) in this zip file?

**Comment by pmasl** [comment]
@udlingal we want to share the Notebook as a whole ready to use artifact, but please also add to your PR the source jar and python outside the zip, so that users can see the source.

**Comment by udlingal** [comment]
This jar file is derivative of existing hadoopbridge connectors used for PolyBase. as it is still Microsoft propitiatory, we cannot share the code to public yet. can we place just jar files now until we can make the code public access ?

**Comment by pmasl** [comment]
Yes, as a sample this is fine for now.

**Comment by pmasl** [comment]
Please add descriptive header on what the tools does. Also, add the note on co-location requirement to the 1st bullet.

**Comment by pmasl** [comment]
Please add descriptive header on what the tools does. Also, add the note on co-location requirement to the 1st bullet.

**Pull request merged**
