### PR TITLE
NEGUST_PYTHON_UPDATES

### PR DESCRIPTION
**Pull request by NelGson**
Updated the ski rental python file to reflect 2017 changes

### CODE REVIEW

**Comment by HumaSatti** [comment]
I get a red error underline for the RxSqlServerData import & RxInSqlServer .

 from revoscalepy import RxInSqlServer

IndentationError: unexpected indent

I have same issue and same run on sql but failed to run on Python or even in VSCode it also fail to run and gave the same error on revoscalepy

**Comment by NelGson** [comment]
Hi, Python in sensitive to indentations, so there must be an extra indentation where it is not supposed to be. Can you try to remove the unnecessary indentation and see if it helps?
I will check the file again to make sure the formatting is ok. Thanks, Nellie

**Comment by NelGson** [comment]
@HumaSatti Btw, which file were you trying to run?

**Comment by HumaSatti** [comment]
@NelGson I'm trying to replicate the Rental prediction and its database TutorialDB data that is provided by microsoft..
https://github.com/Microsoft/sql-server-samples/blob/master/samples/features/machine-learning-services/python/getting-started/rental-prediction/rental_prediction.py 
and this code gave me the error

when run this program got the error ... revoscalepy is missing

from revoscalepy import rx_summary
from revoscalepy import RxInSqlServer
from revoscalepy import RxComputeContext, RxSqlServerData

ModuleNotFoundError: No module named 'revoscalepy'

I have successfully installed sql with R and Python and also in VS ... my code for R and Python is perfectly run on SQL .. My python application run in .net but when I test this code or apply this code then it cannot find this module and gave me the error. I'm also trying to replicate this code for my understanding but again it gave me revoscale error. the link of code which I'm trying is given below.
https://microsoft.github.io/sql-ml-tutorials/python/customerclustering/step/2.html

**Comment by NelGson** [comment]
@HumaSatti Hm...ok, can you add import revoscalepy at the top? Also, it is probably easier if you email me directly: n e g u s t @ microsoft.com. Thanks

**Comment by mmunyoki** [comment]
@HumaSatti  and @NelGson ,
I'm getting the same error (ModuleNotFoundError: No module named 'revoscalepy'). 
Did you ever find a solution? if so, can you please share it ?
Thank you

**Pull request merged**
