### PR TITLE
Added two samples and readmes

### PR DESCRIPTION
**Pull request by sabotta**

### CODE REVIEW

**Comment by sabotta** [comment]
@jodebrui I've included the readmes this time along with the samples, using the readme templates. Can you approve this PR?

**Comment by jodebrui** [comment]
Thanks. The readmes look good.
One further request:
- could you add a README.md to the root of the feature, i.e., data-migration-assistant, to point to the samples under the feature?

**Comment by sabotta** [comment]
@jodebrui I've added the root readme.md file

**Comment by sabotta** [comment]
#sign-off

**Pull request merged**
