### PR TITLE
Update SQLAssessmentAPIQuickStartNotebook.ipynb

### PR DESCRIPTION
**Pull request by SQLvariant**
Small update to add the link, now that the SQL Assessment API Tutorial - Notebook is available.

### CODE REVIEW

**Comment by alexprotsenko** [comment]
Thanks @SQLvariant. @ebruersan can you merge this PR to main?

**Comment by SQLvariant** [comment]
@alexprotsenko I just added a pair of examples for multi-instance Checks to the `SQL Assessment API Tutorial - Notebook`.  I forgot the start a new branch before I committed my changes, so it automatically added them to this PR.  Sorry for causing any confusion.

**Comment by alexprotsenko** [comment]
@SQLvariant No worries. Thank you for enhancing the notebook. Did you know that SQL Asmnt cmdlets support the Registered Server object? You don't have to convert such an object to the Server object before passing it to the cmdlets

**Comment by SQLvariant** [comment]
Doh!  I forgot that we already had a conversation about that @alexprotsenko.  Can you modify my examples to show customers how to do that?  I checked the box to allow maintainers to edit this PR.

**Comment by alexprotsenko** [comment]
@aguzev can you modify Aaron's example so it uses Registered Server object?

**Comment by alexprotsenko** [comment]
@SQLvariant can you add @aguzev to the maintainers?

**Comment by alexprotsenko** [comment]
@ebruersan we need you to merge this PR into main. Can you do it? Aleksei will update the notebook after that

**Comment by SQLvariant** [comment]
I figured how to make the `Central Management Server` example work with `SQLSERVER:\SQLRegistration`. So I updated that one.  I didn't have as much luck with the `Database Engine Server Group` example, so I'll leave that one for @aguzev to update.

**Comment by aguzev** [comment]
@SQLvariant, shouldn't the first example work exactly the same way as the second one? 
```
Get-ChildItem 'SQLSERVER:\SQLRegistration\Database Engine Server Group' | 
Where-Object { $_.mode -ne 'd'} | 
Invoke-SqlAssessment -FlattenOutput |
Write-SqlTableData -ServerInstance localhost -DatabaseName SQLAssessmentDemo -SchemaName Assessment -TableName Results -Force
```

**Pull request merged**
