### PR TITLE
New version of telco customer churn demo

### PR DESCRIPTION
**Pull request by ZhouFang928**
I  have uploaded the new version of telco customer churn demo into my folk repository for sql-server-samples. This new demo leverages open source R, RevoScaleR, and MicrosoftRML packages in SQL Server 2016. Could we update it to the official repository? Thanks.

### CODE REVIEW

**Comment by jodebrui** [comment]
Could you update the README.md to follow the template?
https://github.com/Microsoft/sql-server-samples/blob/master/README_samples_template.md

Thanks,
Jos

**Comment by ZhouFang928** [comment]
I uploaded another version of telco customer churn "Telco Customer Churn v1". That is the version I will use for a blog post. Need I modify the README file for this version? I will move "Telco Customer Churn v3" to a private repository, since it leverages an un-released package RML.

**Comment by jodebrui** [comment]
Yes, please do update the README to follow the template. We want all samples in the repo to follow the template, with the key section being "About this sample", so that the user can very quickly understand what this particular sample is about.

**Comment by maharjananil** [comment]
Hi,

I have also uploaded one SQL File which installed required R packages before running the scripts of telco customer churn into my folk repository for sql-server-samples. The file contains Enabling sp_execute_external_script to run R scripts in SQL Server 2016 and installing required R packages in order to run the Script TelcoChurn-Main.sql and TelcoChurn-Operationalize.sql sucessfully. since we need to install those R packages before we run the scripts in order to avoid the error . 
https://github.com/maharjananil/sql-server-samples/blob/master/samples/features/r-services/Telco%20Customer%20Churn/SQL%20Server/Enabling%20R%20scripts%20to%20run%20and%20Installing%20required%20R%20Packages.sql

https://github.com/Microsoft/sql-server-samples/issues/102
so, I think it will be helpful to upload the new SQL file in official repository too.

Thanks,
Anil Maharjan

**Pull request merged**
