### PR TITLE
Fixed linking reference failure

### PR DESCRIPTION
**Pull request by AleksanderCherepenin**
Fixed linking reference failure

Added checking for Nothing for srcSiteUrl

### CODE REVIEW

**Comment by Matteo-T** [comment]
I've e/mailed Abhishek Kushwaha and asked him to assign this to somebody. When that happens, I can merge (sorry, I'm not an SSRS expert).

@MikeRayMSFT, FYI.

**Comment by Matteo-T** [comment]
@kushabhi4u

**Review by Petebro-MSFT — APPROVED** [review]

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
per @Petebro-MSFT --
#sign-off

**Comment by maggiesMSFT** [comment]
@Matteo-T -- can you merge this PR?

cc @Petebro-MSFT

**Pull request merged**
