### PR TITLE
quick start

### PR DESCRIPTION
**Pull request by CarlRabeler**

### CODE REVIEW

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by jodebrui** [comment]
Could you add a section "About this sample" to the readme files?
See template:
https://github.com/Microsoft/sql-server-samples/blob/master/README_samples_template.md

**Comment by CarlRabeler** [comment]
added

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by jodebrui** [comment]
looks like there are some issues with the formatting of the about section in the elastic pool readme.
could you add an about section to the powershell readme as well?

**Comment by CarlRabeler** [comment]
hmm - will do add to powershell readme
will look at the first article to see what that formatting error is - no validation bot to help me, eh?

**Comment by jodebrui** [comment]
no validation bot, sadly. Also no CI...
If you can help in that space, that would be great

**Comment by CarlRabeler** [comment]
resubmitted

**Comment by CarlRabeler** [comment]
#sign-off

**Pull request merged**
