### PR TITLE
Add Spring Data JPA-based sample

### PR DESCRIPTION
**Pull request by gregturn**
This sample uses Spring Boot + Spring Data JPA alongside SQL Server, illustrating how little effort it takes to setup such an application.

### CODE REVIEW

**Comment by gregturn** [comment]
Question: what about license headers? You may want to choose a licensing strategy and then ensure all the code enforces it.

**Comment by ajlam** [comment]
@gregturn - thanks for your contribution. The rest of the site uses MIT license. Okay with you if I update your sample to align?

**Comment by gregturn** [comment]
Sure!

**Comment by ajlam** [comment]
@gregturn - thanks for your contribution. I'm working on incorporating the Spring samples into the Getting Started site. Will keep you posted on progress.

**Pull request merged**
