### PR TITLE
Reconverted 2 Word docs to PDFs for Data Sync.

### PR DESCRIPTION
**Pull request by douglaslMS**

### CODE REVIEW

**Comment by douglaslMS** [comment]
#sign-off

**Comment by himrathana** [comment]
that you think

**Comment by himrathana** [comment]
and her go to the Microsft. she is do upgrate and she mearring the accoute visualstudio make with work

**Comment by himrathana** [comment]
diff --git a/samples/features/sql-data-sync/Data_Sync_Preview_REST_API.pdf b/samples/features/sql-data-sync/Data_Sync_Preview_REST_API.pdf
index 9a6ad5dd..1b13d794 100644
Binary files a/samples/features/sql-data-sync/Data_Sync_Preview_REST_API.pdf and b/samples/features/sql-data-sync/Data_Sync_Preview_REST_API.pdf differ
diff --git a/samples/features/sql-data-sync/Data_Sync_Preview_full_documentation.pdf b/samples/features/sql-data-sync/Data_Sync_Preview_full_documentation.pdf
index df81285c..1fad2fa6 100644
Binary files a/samples/features/sql-data-sync/Data_Sync_Preview_full_documentation.pdf and b/samples/features/sql-data-sync/Data_Sync_Preview_full_documentation.pdf differ

**Comment by himrathana** [comment]
From 7c18c755b19ea0955a27b1f36d82a3f12f065dcf Mon Sep 17 00:00:00 2001
From: Douglas Laudenschlager <douglasl@microsoft.com>
Date: Tue, 30 May 2017 14:57:10 -0700
Subject: [PATCH] Reconverted 2 Word docs to PDFs for Data Sync.

---
 .../sql-data-sync/Data_Sync_Preview_REST_API.pdf   | Bin 1254144 -> 1225207 bytes
 .../Data_Sync_Preview_full_documentation.pdf       | Bin 2394989 -> 2233410 bytes
 2 files changed, 0 insertions(+), 0 deletions(-)

diff --git a/samples/features/sql-data-sync/Data_Sync_Preview_REST_API.pdf b/samples/features/sql-data-sync/Data_Sync_Preview_REST_API.pdf
index 9a6ad5ddcb21f5a8aa348a252a348e6999e71226..1b13d7945fdca209f0499d841a2baff553b6a193 100644
GIT binary patch
literal 1225207

**Comment by himrathana** [comment]
in the one spot. I don't see. that your user think.

**Comment by himrathana** [comment]
sorry for user. am i go to do the work. for me .

**Comment by himrathana** [comment]
me is say no take her

**Pull request merged**
