### PR TITLE
Parameterization Notebook Sample

### PR DESCRIPTION
**Pull request by VasuBhog**
Add Parameterization Notebook Sample to be used in Azure Data Studio Notebook Docs for users to open directly in ADS.

### CODE REVIEW

**Comment by dzsquared** [comment]
Let's add a readme to the folder with info on the sample - https://github.com/microsoft/sql-server-samples/blob/master/README_samples_template.md - even minimally such that someone who comes across the ipynb knows what to use to open it, why its important, etc.

**Comment by VasuBhog** [comment]
@dzsquared Added a simple readme for now. Will be porting over some other notebooks and can edit the readme then as well.

**Review by dzsquared — APPROVED** [review]

**Comment by dzsquared** [comment]
thank you, this is awesome :)

**Comment by dataonthemove** [comment]
@VasuBhog -- Hi sorry.. kind of odd question.  I'm getting notifications for everything related to this repo ("sql-server-samples")... .. And when I try to unsubscribe using link in email footers I get "Whoops! That unsubscribe link isn't valid for your account."  (shown in attached).

I am not watching this repo but notifications persists.
Do you know why?
thx


Untitled

**Pull request merged**
